siteName: Linkforest
siteDescription: An online discussion platform
emailContact:
twitterURL:
discordURL:
githubURL: 
substackURL:

isDevelopment: true # 生产模式应修改为false
hmacSecret: <insert-your-secret-here> 
noLogToFile: false
csrfOff: false
welcomeCommunity: "general" # 设置为您想要新用户加入的社区名称, 如果不设置请留空。

addr: :8080
sessionCookieName: SID

# MariaDB配置:
dbAddr: 127.0.0.1 # 必须
dbUser: discuit # 必须
dbPassword: discuit # 必须
dbName: discuit # 必须

# ReCAPTCHA或hCaptcha secret和site-key:
captchaSecret:
captchaSiteKey:
disableRateLimits: false # 默认开启速率限制，开发模式可设置为true，即无速率限制

# TLS certificate和key-pair的路径:
certFile:
keyFile:

defaultFeedSort: hot # 默认内容排序为热门
disableForumCreation: false # 开启版块创建，默认为true，即不创建，生产模式应修改为false
forumCreationReqPoints: 10
maxForumsPerUser: 10
imagesFolderPath: "images"
